server:
  port: 8082

spring:
  application:
    name: cloud-consumer
eureka:
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://peer:8761/eureka/
  instance:
      preferIpAddress:  false
      instance-id:      ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
      status-page-url:  http://${spring.cloud.client.hostname}:${server.port}/demo